
import { Deal, Order, Page } from './types';

// Helper to create a date in the future
const getFutureDate = (days: number, hours: number) => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(date.getHours() + hours);
  return date;
};

export const MOCK_HOT_DEALS: Deal[] = [
  {
    id: 'hot-deal-1',
    name: '有機鮮奶吐司麵包 (5入)',
    imageUrl: 'https://picsum.photos/400/300?random=1',
    description: '手工製作，無添加防腐劑，健康美味。',
    currentPrice: 150,
    priceTiers: [
      { quantity: 1, price: 150 },
      { quantity: 10, price: 130 },
      { quantity: 20, price: 110 },
    ],
    participants: 12,
    targetParticipants: 20,
    endTime: getFutureDate(2, 5),
  },
  {
    id: 'hot-deal-2',
    name: '精選挪威鮭魚切片 (500g)',
    imageUrl: 'https://picsum.photos/400/300?random=2',
    description: '新鮮空運，肉質鮮美，富含Omega-3。',
    currentPrice: 380,
    priceTiers: [
      { quantity: 1, price: 380 },
      { quantity: 5, price: 350 },
      { quantity: 10, price: 320 },
    ],
    participants: 4,
    targetParticipants: 10,
    endTime: getFutureDate(1, 10),
  },
  {
    id: 'hot-deal-3',
    name: '日本進口麝香葡萄 (一串)',
    imageUrl: 'https://picsum.photos/400/300?random=3',
    description: '香甜多汁，粒粒飽滿，送禮自用兩相宜。',
    currentPrice: 800,
    priceTiers: [
      { quantity: 1, price: 800 },
      { quantity: 3, price: 750 },
      { quantity: 5, price: 700 },
    ],
    participants: 1,
    targetParticipants: 5,
    endTime: getFutureDate(3, 0),
  },
  {
    id: 'hot-deal-4',
    name: '高級手工蛋捲禮盒 (20入)',
    imageUrl: 'https://picsum.photos/400/300?random=4',
    description: '酥脆香濃，獨立包裝，方便分享。',
    currentPrice: 280,
    priceTiers: [
      { quantity: 1, price: 280 },
      { quantity: 10, price: 250 },
      { quantity: 20, price: 220 },
    ],
    participants: 8,
    targetParticipants: 20,
    endTime: getFutureDate(0, 18),
  },
];

export const MOCK_NEARBY_DEALS: Deal[] = [
  {
    id: 'nearby-deal-1',
    name: '現烤法式可頌 (6入)',
    imageUrl: 'https://picsum.photos/400/300?random=5',
    description: '外酥內軟，每日新鮮烘焙，搭配咖啡更美味。',
    currentPrice: 180,
    priceTiers: [
      { quantity: 1, price: 180 },
      { quantity: 5, price: 160 },
      { quantity: 10, price: 140 },
    ],
    participants: 7,
    targetParticipants: 10,
    endTime: getFutureDate(0, 3),
    distanceKm: 0.5,
    savingsAmount: 20,
  },
  {
    id: 'nearby-deal-2',
    name: '當季新鮮水果禮盒',
    imageUrl: 'https://picsum.photos/400/300?random=6',
    description: '嚴選當季最新鮮水果，營養又健康。',
    currentPrice: 450,
    priceTiers: [
      { quantity: 1, price: 450 },
      { quantity: 3, price: 400 },
      { quantity: 5, price: 350 },
    ],
    participants: 2,
    targetParticipants: 5,
    endTime: getFutureDate(1, 15),
    distanceKm: 1.2,
    savingsAmount: 50,
  },
  {
    id: 'nearby-deal-3',
    name: '手工水餃 (100顆裝)',
    imageUrl: 'https://picsum.photos/400/300?random=7',
    description: '多種口味，皮薄餡大，冷凍保存方便。',
    currentPrice: 300,
    priceTiers: [
      { quantity: 1, price: 300 },
      { quantity: 3, price: 280 },
      { quantity: 5, price: 250 },
    ],
    participants: 9,
    targetParticipants: 10,
    endTime: getFutureDate(0, 20),
    distanceKm: 0.8,
    savingsAmount: 20,
  },
  {
    id: 'nearby-deal-4',
    name: '天然蜂蜜檸檬飲 (10瓶)',
    imageUrl: 'https://picsum.photos/400/300?random=8',
    description: '天然蜂蜜，新鮮檸檬，清涼解渴。',
    currentPrice: 220,
    priceTiers: [
      { quantity: 1, price: 220 },
      { quantity: 5, price: 200 },
      { quantity: 10, price: 180 },
    ],
    participants: 3,
    targetParticipants: 10,
    endTime: getFutureDate(2, 12),
    distanceKm: 2.1,
    savingsAmount: 20,
  },
];

export const MOCK_DEAL_DETAILS: Deal = {
  id: 'deal-details-example',
  name: '頂級安格斯牛排 (200g x 2片)',
  imageUrl: 'https://picsum.photos/600/400?random=9',
  description: '嚴選美國安格斯牛，油花均勻，肉質鮮嫩，在家也能享受高級餐廳的美味。',
  currentPrice: 699,
  priceTiers: [
    { quantity: 1, price: 799 },
    { quantity: 10, price: 749 },
    { quantity: 25, price: 699 },
    { quantity: 50, price: 649 },
  ],
  participants: 28,
  targetParticipants: 50,
  endTime: getFutureDate(4, 8),
};

export const MOCK_ORDERS: Order[] = [
  {
    id: 'order-1',
    dealId: 'hot-deal-1',
    dealName: '有機鮮奶吐司麵包 (5入)',
    buyerName: '張小姐',
    quantity: 2,
    totalAmount: 300,
    status: 'pending',
    orderDate: new Date('2024-07-20T10:00:00Z'),
  },
  {
    id: 'order-2',
    dealId: 'nearby-deal-1',
    dealName: '現烤法式可頌 (6入)',
    buyerName: '李先生',
    quantity: 1,
    totalAmount: 180,
    status: 'pending',
    orderDate: new Date('2024-07-20T11:30:00Z'),
  },
  {
    id: 'order-3',
    dealId: 'hot-deal-2',
    dealName: '精選挪威鮭魚切片 (500g)',
    buyerName: '王太太',
    quantity: 1,
    totalAmount: 380,
    status: 'completed',
    orderDate: new Date('2024-07-19T14:00:00Z'),
  },
  {
    id: 'order-4',
    dealId: 'hot-deal-1',
    dealName: '有機鮮奶吐司麵包 (5入)',
    buyerName: '陳先生',
    quantity: 3,
    totalAmount: 450,
    status: 'pending',
    orderDate: new Date('2024-07-20T09:00:00Z'),
  },
  {
    id: 'order-5',
    dealId: 'nearby-deal-3',
    dealName: '手工水餃 (100顆裝)',
    buyerName: '林小姐',
    quantity: 2,
    totalAmount: 600,
    status: 'pending',
    orderDate: new Date('2024-07-19T18:00:00Z'),
  },
  {
    id: 'order-6',
    dealId: 'hot-deal-3',
    dealName: '日本進口麝香葡萄 (一串)',
    buyerName: '高太太',
    quantity: 1,
    totalAmount: 800,
    status: 'completed',
    orderDate: new Date('2024-07-18T10:00:00Z'),
  },
  {
    id: 'order-7',
    dealId: 'hot-deal-4',
    dealName: '高級手工蛋捲禮盒 (20入)',
    buyerName: '黃先生',
    quantity: 2,
    totalAmount: 560,
    status: 'pending',
    orderDate: new Date('2024-07-20T15:00:00Z'),
  },
  {
    id: 'order-8',
    dealId: 'hot-deal-1',
    dealName: '有機鮮奶吐司麵包 (5入)',
    buyerName: '吳小姐',
    quantity: 1,
    totalAmount: 150,
    status: 'completed',
    orderDate: new Date('2024-07-18T09:00:00Z'),
  },
];
